### ISSUE TITLE
tools/namelist.py: IOError no such file .../GlyphsInfo/GlyphData.xml

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#1174]
[./tools/namelist.py](https://github.com/google/fonts/blob/master/tools/namelist.py) is broken.

GlyphData.xml has been deleted which is needed for the module `util.filter_lists` to work.

Here's the traceback I get.

```
(env)Marc:fonts marc$ python tools/namelist.py
Traceback (most recent call last):
  File "tools/namelist.py", line 44, in <module>
    from util  import filter_lists
  File "/Users/marc/Documents/googlefonts/fonts/tools/util/filter_lists.py", line 20, in <module>
    from glyphdata import DATA as GlyphData
  File "/Users/marc/Documents/googlefonts/fonts/tools/util/glyphdata.py", line 73, in <module>
    DATA = _build_data(_fetch_all_glyphs())
  File "/Users/marc/Documents/googlefonts/fonts/tools/util/glyphdata.py", line 51, in _fetch_all_glyphs
    for glyph in etree.parse(full_filename).findall("glyph"):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: u'/Users/marc/Documents/googlefonts/fonts/tools/util/GlyphsInfo/GlyphData.xml'
```

We should also have a functional test for each script in this repo.

**Comment by graphicore** [comment]
`git submodule update --init --recursive`

**Comment by m4rc1e** [comment]
Thank @graphicore

**Comment by davelab6** [comment]
Before closing please fix the docs to add more notices about this requirement

**Comment by m4rc1e** [comment]
@davelab6 sure, I'll add it to the [./tools/README.md](https://github.com/google/fonts/blob/master/tools/README.md)

**Comment by davelab6** [comment]
Thanks Marc!
