### ISSUE TITLE
SeoulHangang GSUB + vmtx tables can't be TTX'd?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1513]
@m4rc1e one of the recently added Korean fonts fails to roundtrip TTX; whats up with that?

```
ERROR: An exception occurred during the decompilation of the 'GSUB' table
error: unpack requires a string argument of length 4
ERROR: An exception occurred during the decompilation of the 'vmtx' table
    ofl/seoulhangang/SeoulHangang-Light.ttf
    ofl/seoulhangang/SeoulHangang-Medium.ttf
    ofl/seoulnamsan/SeoulNamsan-Bold.ttf
    ofl/seoulnamsan/SeoulNamsan-Light.ttf
    ofl/seoulnamsan/SeoulNamsan-Medium.ttf
```

**Comment by m4rc1e** [comment]
Full traceback

```
Dumping "/Users/marc/Documents/googlefonts/fonts/ofl/seoulhangang/SeoulHangang-Medium.ttf" to "/Users/marc/Documents/googlefonts/fonts/ofl/seoulhangang/SeoulHangang-Medium.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
ERROR: An exception occurred during the decompilation of the 'GSUB' table
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/__init__.py", line 420, in __getitem__
    table.decompile(data, self)
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 49, in decompile
    self.table.decompile(reader, font)
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 613, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 286, in read
    value = reader.readLong()
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 184, in readLong
    value, = struct.unpack(">l", self.data[pos:newpos])
error: unpack requires a string argument of length 4
Dumping 'GSUB' table...
Dumping 'vhea' table...
ERROR: An exception occurred during the decompilation of the 'vmtx' table
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/__init__.py", line 420, in __getitem__
    table.decompile(data, self)
  File "/Library/Python/2.7/site-packages/fontTools/ttLib/tables/_h_m_t_x.py", line 60, in decompile
    self.metrics[glyphName] = (lastAdvance, sideBearings[i])
IndexError: array index out of range
Dumping 'vmtx' table...
```
