### ISSUE TITLE
Instances created from some Noto VFs fail remove overlaps

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#3365]
```
fonttools varLib.instancer ofl/notosansethiopic/NotoSansEthiopic\[wdth\,wght\].ttf wdth=100 wght=800 --remove-overlaps

Restricting axes: {'wdth': 100.0, 'wght': 800.0}
Loading variable font
Normalized limits: {'wght': 0.78997802734375, 'wdth': 0.0}
Instantiating glyf/gvar tables
Dropping HVAR table
Instantiating GDEF and GPOS tables
Dropping avar table
Dropping fvar table
Pruning name table
Removing overlaps from glyf table
Traceback (most recent call last):
  File "/tmp/venv/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/venv/lib/python3.9/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/tmp/venv/lib/python3.9/site-packages/fontTools/varLib/instancer/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/private/tmp/venv/lib/python3.9/site-packages/fontTools/varLib/instancer/__init__.py", line 1408, in main
    instantiateVariableFont(
  File "/private/tmp/venv/lib/python3.9/site-packages/fontTools/varLib/instancer/__init__.py", line 1250, in instantiateVariableFont
    removeOverlaps(varfont)
  File "/private/tmp/venv/lib/python3.9/site-packages/fontTools/ttLib/removeOverlaps.py", line 162, in removeOverlaps
    if removeTTGlyphOverlaps(
  File "/private/tmp/venv/lib/python3.9/site-packages/fontTools/ttLib/removeOverlaps.py", line 96, in removeTTGlyphOverlaps
    path2 = pathops.simplify(path, clockwise=path.clockwise)
  File "src/python/pathops/_pathops.pyx", line 1476, in pathops._pathops.simplify
  File "src/python/pathops/_pathops.pyx", line 1487, in pathops._pathops.simplify
pathops._pathops.PathOpsError: operation did not succeed
```

**Comment by rsheeter** [comment]
Not sure if this is something to do with the font or an issue with simplify itself

**Comment by rsheeter** [comment]
@davelab6 perhaps instancing a few common locations would be a good bakery test for VFs?

**Comment by rsheeter** [comment]
This occurs for Telugu as well:

```
fonttools varLib.instancer ofl/notosanstelugu/NotoSansTelugu\[wdth\,wght\].ttf wdth=75 wght=100 --remove-overlaps
fonttools varLib.instancer ofl/notosansteluguui/NotoSansTeluguUI\[wdth\,wght\].ttf wdth=75 wght=100 --remove-overlaps
```

Instances create fine at many other locations, something about the outlines at these positions seems to upset simplify.

**Comment by davelab6** [comment]
Agreed, good test fail cases. @moyogo could you take a look at the Fonts

**Comment by anthrotype** [comment]
If I print the name of the glyph that fails with PathOpsError, I get 'cche.eth' and 'che.eth'. This is for NotoSansEthiopic\[wdth\,wght\].ttf wdth=100 wght=800. I don't know why skia-pathops fails like that with those specific glyphs. I don't think there's anything wrong with the glyphs per se. I will try to reproduce using only skia and file an issue with upstream.

**Comment by thlinard** [comment]
If the Noto VFs are going to be corrected upstream, it would be nice to raise #3267 too: I haven't seen a single Noto VF with a correct `STAT` table.

**Comment by rsheeter** [comment]
@marekjez86 is fixing Noto STATs feasible?

**Comment by moyogo** [comment]
For NotoSansTelugu, the PathOpsError is raise when removeOverlaps is run on ddauvoweltelu and ddhauvoweltelu.

I couldn't see anything wrong with these nor the ones in NotoSansEthiopic.

@rsheeter @thlinard We can fix the STAT tables.

**Comment by rsheeter** [comment]
Anything unusual about them? Any pattern present in all the kerploding glyphs?

**Comment by anthrotype** [comment]
I filed a bug upstream https://bugs.chromium.org/p/skia/issues/detail?id=11958

**Comment by rsheeter** [comment]
@anthrotype heads up, I'm observing the problem even after the rounding fix

**Comment by rsheeter** [comment]
Our automation reported `fontTools.ttLib.removeOverlaps.RemoveOverlapsError: Failed to remove overlaps from glyph 'uni1328'` at width 87.5, weight 800. Reproduces, albeit with different glyph reported, using fonttools cli:

```
fonttools varLib.instancer ofl/notosansethiopic/NotoSansEthiopic\[wdth\,wght\].ttf wdth=87.5 wght=800 --remove-overlaps
...blah blah blah...
Traceback (most recent call last):
  File ".../fontTools/ttLib/removeOverlaps.py", line 110, in _simplify
    path = pathops.simplify(path, clockwise=path.clockwise)
  File "src/python/pathops/_pathops.pyx", line 1476, in pathops._pathops.simplify
  File "src/python/pathops/_pathops.pyx", line 1487, in pathops._pathops.simplify
pathops._pathops.PathOpsError: operation did not succeed

The above exception was the direct cause of the following exception:

  ...snip...
  File ".../fontTools/varLib/instancer/__main__.py", line 5, in <module>
    sys.exit(main())
  File ".../fontTools/varLib/instancer/__init__.py", line 1409, in main
    instantiateVariableFont(
  File ".../fontTools/varLib/instancer/__init__.py", line 1251, in instantiateVariableFont
    removeOverlaps(varfont)
  File ".../fontTools/ttLib/removeOverlaps.py", line 209, in removeOverlaps
    if removeTTGlyphOverlaps(
  File ".../fontTools/ttLib/removeOverlaps.py", line 143, in removeTTGlyphOverlaps
    path2 = _simplify(path, glyphName)
  File ".../fontTools/ttLib/removeOverlaps.py", line 119, in _simplify
    raise RemoveOverlapsError(
fontTools.ttLib.removeOverlaps.RemoveOverlapsError: Failed to remove overlaps from glyph 'cchee.eth'
```

**Comment by anthrotype** [comment]
cc @nathan-williams
