### ISSUE TITLE
Upstream Makefiles don't consistently succeed

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#4773]
https://github.com/googlefonts/oxidize/issues/25#issuecomment-1153000702 asserts `make build` should work on upstream repos. However, most of them don't have a Makefile and the ones that do seem not to consistently work. I located 24 repos that have Makefiles and 4 out of the 5 I tried failed:

```
(cd changa && time make build; rm -rf venv)
	fontmake.errors.FontmakeError: In 'Changa.glyphs' -> 'master_ufo/Changa.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'exclam', 'exclamdown', 'jeem-ar', 'jeem-ar.fina', 'question', 'question-ar', 'questiondown', 'tcheh-ar', 'tcheh-ar.fina'
	make: *** [Makefile:19: build.stamp] Error 1

(cd elmessiri && time make build; rm -rf venv)
	# IT WORKS!

(cd murecho && time make build; rm -rf venv)
	fontmake.errors.FontmakeError: In 'Murecho.glyphs' -> 'master_ufo/Murecho.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'bi-kata', 'bu-hira', 'do-hira', 'gi-hira', 'ka_semivoicedcomb-kana-kata', 'ki_semivoicedcomb-kana-hira', 'ki_semivoicedcomb-kana-kata', 'tu_semivoicedcomb-kana-kata'
	make: *** [Makefile:19: build.stamp] Error 1

(cd dosis && time make build; rm -rf venv)
	fontmake.errors.FontmakeError: In 'Dosis.glyphs' -> 'master_ufo/Dosis.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'Abrevedotbelow', 'Abrevetilde', 'Acircumflexacute', 'Acircumflexdotbelow', 'Acircumflexgrave', 'Acircumflextilde', 'Adotbelow', 'Ecircumflexacute', 'Ecircumflexdotbelow', 'Ecircumflexgrave', 'Ecircumflextilde', 'Edotbelow', 'Idotbelow', 'Ocircumflexacute', 'Ocircumflexdotbelow', 'Ocircumflexgrave', 'Ocircumflextilde', 'Odotbelow', 'Ohorndotbelow', 'Udotbelow', 'Uhorndotbelow', 'Ydotbelow', 'abrevedotbelow', 'abrevetilde', 'acircumflexacute', 'acircumflexdotbelow', 'acircumflexgrave', 'acircumflextilde', 'adotbelow', 'brevecomb_tildecomb', 'circumflexcomb_acutecomb', 'circumflexcomb_gravecomb', 'circumflexcomb_tildecomb', 'dotbelowcomb', 'ecircumflexacute', 'ecircumflexdotbelow', 'ecircumflexgrave', 'ecircumflextilde', 'edotbelow', 'idotbelow', 'ocircumflexacute', 'ocircumflexdotbelow', 'ocircumflexgrave', 'ocircumflextilde', 'odotbelow', 'ohorndotbelow', 'udotbelow', 'uhorndotbelow', 'ydotbelow'
	mv fonts/variable/Dosis[wght].ttf.fix fonts/variable/Dosis[wght].ttf

(cd faustina && time make build; rm -rf venv)
	Traceback (most recent call last):
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/bin/gftools-builder.py", line 83, in <module>
	    builder.build()
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 197, in build
	    self.build_static()
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 414, in build_static
	    self.build_a_static_format(
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 462, in build_a_static_format
	    postprocessor(fontfile)
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 485, in post_process_ttf
	    autohint(filename, filename, add_script=self.config["ttfaUseScript"])
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/lib/python3.9/site-packages/gftools/builder/autohint.py", line 97, in autohint
	    ttfautohint(**ttfautohint_parse_args([infile, outfile, *args]))
	  File "/usr/local/google/home/rsheeter/oss/compiler/upstream_repos/faustina/venv/lib/python3.9/site-packages/ttfautohint/__init__.py", line 124, in ttfautohint
	    raise TAError(rv, **error_callback_data.kwargs)
	ttfautohint.errors.TAError: 0xF5: font already processed by ttfautohint
	make: *** [Makefile:19: build.stamp] Error 1

# As yet untested
(cd rokkitt && time make build; rm -rf venv)
(cd outfit && time make build; rm -rf venv)
(cd archivonarrow && time make build; rm -rf venv)
(cd manjari && time make build; rm -rf venv)
(cd hahmlet && time make build; rm -rf venv)
(cd chilanka && time make build; rm -rf venv)
(cd dancingscript && time make build; rm -rf venv)
(cd kosugimaru && time make build; rm -rf venv)
(cd bakbakone && time make build; rm -rf venv)
(cd mulish && time make build; rm -rf venv)
(cd kosugi && time make build; rm -rf venv)
(cd birthstonebounce && time make build; rm -rf venv)
(cd signika && time make build; rm -rf venv)
(cd signikanegative && time make build; rm -rf venv)
(cd museomoderno && time make build; rm -rf venv)
(cd overpassmono && time make build; rm -rf venv)
(cd overpass && time make build; rm -rf venv)
(cd worksans && time make build; rm -rf venv)
(cd rosario && time make build; rm -rf venv)
```

**Comment by simoncozens** [comment]
The problem with changa and dosis is to do with https://github.com/googlefonts/ufo2ft/issues/507 and the order of filters: decomposing components, flattening components, and decomposing transformed components.

**Comment by m4rc1e** [comment]
I've done some further digging. Most of these fonts are failing due to https://github.com/googlefonts/ufo2ft/issues/621. I'll have a solution for it soonish.

**Comment by chrissimpkins** [comment]
> I've done some further digging. Most of these fonts are failing due to [googlefonts/ufo2ft#621](https://github.com/googlefonts/ufo2ft/issues/621).

Fixed by https://github.com/googlefonts/ufo2ft/pull/625

**Comment by rsheeter** [comment]
On retry 4 of 5 now work:

```

  (cd changa && time make build; rm -rf venv)
  # works! real 1m11.377s

  (cd elmessiri && time make build; rm -rf venv)
  # works! real 0m51.198s

  (cd murecho && time make build; rm -rf venv)
  # works! real 10m47.340s

  (cd dosis && time make build; rm -rf venv)
  # works! real 1m5.195s

  (cd faustina && time make build; rm -rf venv)
  # fails, lots of errors about ERROR:ufo2ft.filters:Failed to load filter: {'name': 'AddExtremes'}

INFO:fontmake.font_project:Autohinting /tmp/tmp9nxjzaua/Faustina-Bold.ttf
INFO:fontmake.font_project:Building TTF for Faustina-ExtraBold
ERROR:ufo2ft.filters:Failed to load filter: {'name': 'AddExtremes'}
Traceback (most recent call last):
  File "faustina/venv/lib/python3.10/site-packages/ufo2ft/filters/__init__.py", line 64, in loadFilters
    filterClass = getFilterClass(filterDict["name"], namespace)
  File "faustina/venv/lib/python3.10/site-packages/ufo2ft/filters/__init__.py", line 49, in getFilterClass
    module = importlib.import_module(".".join([pkg, moduleName]))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ufo2ft.filters.addExtremes'
INFO:fontmake.font_project:Saving /tmp/tmpbe4mkmyl.ttf
INFO:fontmake.font_project:Autohinting /tmp/tmp9nxjzaua/Faustina-ExtraBold.ttf
INFO:GFBuilder:Created static font ../fonts/ttf/Faustina-ExtraBold.ttf
Traceback (most recent call last):
  File "faustina/venv/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "faustina/venv/lib/python3.10/site-packages/gftools/builder/__init__.py", line 197, in build
    self.build_static()
  File "faustina/venv/lib/python3.10/site-packages/gftools/builder/__init__.py", line 414, in build_static
    self.build_a_static_format(
  File "faustina/venv/lib/python3.10/site-packages/gftools/builder/__init__.py", line 462, in build_a_static_format
    postprocessor(fontfile)
  File "faustina/venv/lib/python3.10/site-packages/gftools/builder/__init__.py", line 485, in post_process_ttf
    autohint(filename, filename, add_script=self.config["ttfaUseScript"])
  File "faustina/venv/lib/python3.10/site-packages/gftools/builder/autohint.py", line 97, in autohint
    ttfautohint(**ttfautohint_parse_args([infile, outfile, *args]))
  File "faustina/venv/lib/python3.10/site-packages/ttfautohint/__init__.py", line 124, in ttfautohint
    raise TAError(rv, **error_callback_data.kwargs)
ttfautohint.errors.TAError: 0xF5: font already processed by ttfautohint
make: *** [Makefile:19: build.stamp] Error 1
```

**Comment by anthrotype** [comment]
the logging message `ERROR:ufo2ft.filters:Failed to load filter: {'name': 'AddExtremes'}` is suspicious, it looks like somebody added a custom filter named "AddExtremes" without its module namespace, so ufo2ft thinks it comes from the set of built-in filters, which is not the case, hence it fails to import it.

The error about ttfautohint failing to process the same font twice is also strange, I don't know what's going on there.

@m4rc1e is this something you could look into at some point?

**Comment by rsheeter** [comment]
Can we have the makefile and gfbuilder repos build themselves for CI? - would be nice to trust things will build.

**Comment by rsheeter** [comment]
I'm seeing Noto families that have an upstream.yaml that lack `repository_url` even when it seemingly exists:

```yaml
cat ofl/notosansarmenian/upstream.yaml 
archive: https://github.com/notofonts/armenian/releases/download/NotoSansArmenian-v2.007/NotoSansArmenian-v2.007.zip
branch: main
files:
  ARTICLE.en_us.html: article/ARTICLE.en_us.html
  OFL.txt: OFL.txt
  DESCRIPTION.en_us.html: DESCRIPTION.en_us.html
  NotoSansArmenian/googlefonts/variable-ttf/NotoSansArmenian[wdth,wght].ttf: NotoSansArmenian[wdth,wght].ttf
```

@simoncozens shouldn't ^ have `repository_url: https://github.com/notofonts/armenian`?

**Comment by davelab6** [comment]
I think we created those repos after the PRs Marek made originally, but yes, would be great to better lint these. @felipesanches any fb check ideas come to mind?

**Comment by rsheeter** [comment]
Checking for GH based archive and no repo url - or with a repo url that doesn't match - might be a nice start?

**Comment by simoncozens** [comment]
The upstream.yml files are created by gftools-packager, which records that a font came either from a repo or from an archive but not both.

**Comment by rsheeter** [comment]
> the onboarding process is oriented around binaries, not sources

That's an interesting point. We will need to start changing to focus on sources. Summon @davelab6 @chrissimpkins .

Is there any reason that adding the repo url where today we have only a GH archive ref would be bad? - we can add a check that they match to increase odds of consistency.

**Comment by RosaWagner** [comment]
Is the original question of this issue answered and therefore can we close it?

**Comment by rsheeter** [comment]
I'm not sure; @m4rc1e did we fix the makefiles?

**Comment by m4rc1e** [comment]
I haven't had an opportunity to look at this yet. I'm hoping builder2 and Simon's collection wide font building can help speed up this task.

**Comment by chrissimpkins** [comment]
Moving to backlog for now until we understand priority and capacity to take this on.

**Comment by rsheeter** [comment]
I don't have a great answer for priority. I can give a little context. As part of landing fontc we will want to move to a source oriented onboarding process. This seems at risk of blocking or impeding that. We aren't quite there yet so it's not _urgent_ yet, but we should expect having good data on upstream sources to become more important over time.

**Comment by davelab6** [comment]
I'm closing this as it is really a child of #7358 and @simoncozens will drive this in Q2
