### ISSUE TITLE
Exception in the Run Diffbrowsers step of the QA pipeline

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#5818]
@m4rc1e This permissions exception was raised in [this job](https://github.com/google/fonts/actions/runs/3980076013/jobs/6822918659) on #5817:

```
A report in GitHub Markdown format which can be useful
 for posting issues on a GitHub issue tracker has been
 saved to "out/taiheritagepro_qa/Fontbakery/report.md"
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/bin/gftools", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/gftools/scripts/qa.py", line 255, in main
    qa.post_to_github(args.out_url)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/gftools/qa.py", line 122, in post_to_github
    client = GitHubClient(repo_owner, repo_name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/gftools/github.py", line 15, in __init__
    raise Exception("GH_TOKEN environment variable not set")
Exception: GH_TOKEN environment variable not set
Error: Process completed with exit code 1.
```

**Comment by chrissimpkins** [comment]
Also seen in https://github.com/google/fonts/pull/5819

**Comment by m4rc1e** [comment]
I'm rewriting the shell script which chooses which qa task to run. Testing on my branch for the time being, https://github.com/m4rc1e/fonts/pull/260
